###
# curl -H "Authorization: Bearer IDE_A_TOKENED"
#  "http://localhost:5001/api/audit-logs?tournamentId=69c27bd64f4463b22ae08d7b&limit=50"
GET http://localhost:5001/api/audit-logs?tournamentId=69c27bd64f4463b22ae08d7b&limit=50
Authorization: Bearer IDE_A_TOKENED

###
